export default {
  created_at: 'Mon Sep 18 21:23:54 +0000 2017',
  id: 909890750669877200,
  id_str: '909890750669877249',
  text:
    'RT @dave_lunny: Slight changes for DOM Attributes in React 16 https://t.co/mETp9OP1KW #reactjs #javascript #webdevelopment #html https://t.…',
  truncated: false,
  entities: {
    hashtags: [
      {
        text: 'reactjs',
        indices: [86, 94],
      },
      {
        text: 'javascript',
        indices: [95, 106],
      },
      {
        text: 'webdevelopment',
        indices: [107, 122],
      },
      {
        text: 'html',
        indices: [123, 128],
      },
    ],
    symbols: [],
    user_mentions: [
      {
        screen_name: 'dave_lunny',
        name: 'himynameisdave',
        id: 2290190784,
        id_str: '2290190784',
        indices: [3, 14],
      },
    ],
    urls: [
      {
        url: 'https://t.co/mETp9OP1KW',
        expanded_url: 'http://bit.ly/2ftgVcN',
        display_url: 'bit.ly/2ftgVcN',
        indices: [62, 85],
      },
    ],
  },
  metadata: {
    iso_language_code: 'en',
    result_type: 'recent',
  },
  source: '<a href="http://simbasystems.com" rel="nofollow">javascriptdigest</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 2704581690,
    id_str: '2704581690',
    name: 'Javascript Digest',
    screen_name: 'javascriptd',
    location: 'Everywhere ',
    description: 'Javascript Digest brought to you by http://t.co/rHlyfe7p7r',
    url: null,
    entities: {
      description: {
        urls: [
          {
            url: 'http://t.co/rHlyfe7p7r',
            expanded_url: 'http://SimbaSystems.com',
            display_url: 'SimbaSystems.com',
            indices: [36, 58],
          },
        ],
      },
    },
    protected: false,
    followers_count: 22126,
    friends_count: 4,
    listed_count: 8650,
    created_at: 'Sun Aug 03 17:58:20 +0000 2014',
    favourites_count: 134,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 1036730,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '022330',
    profile_background_image_url: 'http://abs.twimg.com/images/themes/theme15/bg.png',
    profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme15/bg.png',
    profile_background_tile: false,
    profile_image_url: 'http://pbs.twimg.com/profile_images/544034757730779136/-jOL7GnN_normal.jpeg',
    profile_image_url_https: 'https://pbs.twimg.com/profile_images/544034757730779136/-jOL7GnN_normal.jpeg',
    profile_link_color: '0084B4',
    profile_sidebar_border_color: 'A8C7F7',
    profile_sidebar_fill_color: 'C0DFEC',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false,
    translator_type: 'none',
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: 'Mon Sep 18 15:10:08 +0000 2017',
    id: 909796688231112700,
    id_str: '909796688231112704',
    text:
      'Slight changes for DOM Attributes in React 16 https://t.co/mETp9OP1KW #reactjs #javascript #webdevelopment #html https://t.co/8cJEhVFV2C',
    truncated: false,
    entities: {
      hashtags: [
        {
          text: 'reactjs',
          indices: [70, 78],
        },
        {
          text: 'javascript',
          indices: [79, 90],
        },
        {
          text: 'webdevelopment',
          indices: [91, 106],
        },
        {
          text: 'html',
          indices: [107, 112],
        },
      ],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: 'https://t.co/mETp9OP1KW',
          expanded_url: 'http://bit.ly/2ftgVcN',
          display_url: 'bit.ly/2ftgVcN',
          indices: [46, 69],
        },
      ],
      media: [
        {
          id: 909796686125457400,
          id_str: '909796686125457408',
          indices: [113, 136],
          media_url: 'http://pbs.twimg.com/media/DKA_RAZV4AAgAAR.jpg',
          media_url_https: 'https://pbs.twimg.com/media/DKA_RAZV4AAgAAR.jpg',
          url: 'https://t.co/8cJEhVFV2C',
          display_url: 'pic.twitter.com/8cJEhVFV2C',
          expanded_url: 'https://twitter.com/dave_lunny/status/909796688231112704/photo/1',
          type: 'photo',
          sizes: {
            medium: {
              w: 1200,
              h: 630,
              resize: 'fit',
            },
            small: {
              w: 680,
              h: 357,
              resize: 'fit',
            },
            thumb: {
              w: 150,
              h: 150,
              resize: 'crop',
            },
            large: {
              w: 1200,
              h: 630,
              resize: 'fit',
            },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 909796686125457400,
          id_str: '909796686125457408',
          indices: [113, 136],
          media_url: 'http://pbs.twimg.com/media/DKA_RAZV4AAgAAR.jpg',
          media_url_https: 'https://pbs.twimg.com/media/DKA_RAZV4AAgAAR.jpg',
          url: 'https://t.co/8cJEhVFV2C',
          display_url: 'pic.twitter.com/8cJEhVFV2C',
          expanded_url: 'https://twitter.com/dave_lunny/status/909796688231112704/photo/1',
          type: 'photo',
          sizes: {
            medium: {
              w: 1200,
              h: 630,
              resize: 'fit',
            },
            small: {
              w: 680,
              h: 357,
              resize: 'fit',
            },
            thumb: {
              w: 150,
              h: 150,
              resize: 'crop',
            },
            large: {
              w: 1200,
              h: 630,
              resize: 'fit',
            },
          },
        },
      ],
    },
    metadata: {
      iso_language_code: 'en',
      result_type: 'recent',
    },
    source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 2290190784,
      id_str: '2290190784',
      name: 'himynameisdave',
      screen_name: 'dave_lunny',
      location: 'Vancouver, Canada',
      description: 'dev @7Geese 👌 I love making me some internets.',
      url: 'https://t.co/i8r8uM3D2T',
      entities: {
        url: {
          urls: [
            {
              url: 'https://t.co/i8r8uM3D2T',
              expanded_url: 'http://himynameisdave.com/',
              display_url: 'himynameisdave.com',
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 1068,
      friends_count: 1844,
      listed_count: 475,
      created_at: 'Mon Jan 13 20:50:00 +0000 2014',
      favourites_count: 4518,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 4799,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'FFC107',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/638559669129052161/3kUBX1BG_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/638559669129052161/3kUBX1BG_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2290190784/1503990018',
      profile_link_color: 'FFC107',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 4,
    favorite_count: 4,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en',
  },
  is_quote_status: false,
  retweet_count: 4,
  favorite_count: 0,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en',
};
